config/routes.rb
Rails.application.routes.draw do

  resources :indicator_junior_companies
  resources :indicator_federations
  resources :indicators
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "/perfomance_evaluation/:role_id" => "static_pages#perfomance_evaluation"
  get "/perfomance_result" => "static_pages#perfomance_result"
  get "/perfomance_areas" => "static_pages#perfomance_areas"
  get "/home" => "static_pages#home"
  get "/ajax_perfomance_user_save" => "static_pages#ajax_perfomance_user_save"

  get "/perfomance_answer" => "static_pages#perfomance_answer"
  devise_for :users, :controllers => { registrations: 'devise/registrations' }
  resources :questions
  resources :dimensions
  resources :perfomances
  resources :roles
  resources :areas
  resources :organograms
  resources :junior_companies
  resources :federations
  resources :cities
  resources :states
  resources :countries
  resources :roles

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to:organogram
  has_many:role
  has_many :subareas, class_name: "Area",
                          foreign_key: "subarea_id"
 
  belongs_to :subarea, class_name: "Area"
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to:state
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many:states
end

app/models/dimension.rb
class Dimension < ActiveRecord::Base
  belongs_to :perfomance
  has_many :questions
  has_many :perfomance_answers
end

app/models/federation.rb
class Federation < ActiveRecord::Base
  has_many :junior_companies
  has_many :organograms
  has_many :perfomaces
  has_many :indicator_federations
  has_many :indicators, through: :indicator_federations
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :indicator_junior_companies
  has_many :junior_companies, through: :indicator_junior_companies
  has_many :indicator_federations
  has_many :federations, through: :indicator_federations
end

app/models/junior_company.rb
class JuniorCompany < ActiveRecord::Base
  belongs_to :federation
  has_many :organograms
  has_many :perfomances
  has_many :indicator_junior_companies
  has_many :indicator, through: :indicator_junior_companies
end

app/models/organogram.rb
class Organogram < ActiveRecord::Base
  belongs_to:federation
  belongs_to:junior_company
  has_many:areas
  has_many:roles
end

app/models/perfomance.rb
class Perfomance < ActiveRecord::Base
  belongs_to :junior_companies
  belongs_to :federations
  belongs_to :role
  has_many :dimensions
  has_many :perfomance_answers
end

app/models/perfomance_answer.rb
class PerfomanceAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :perfomance
  belongs_to :dimension
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :dimension
  has_many :perfomance_answers
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to:organograms
  belongs_to:areas
  has_many:perfomances
  has_many:users
  has_many :suproles, class_name: "Role",
                          foreign_key: "suprole_id"
 
  belongs_to :suprole, class_name: "Role"
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to:country
  has_many:cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/organograms_controller.rb
class OrganogramsController < ApplicationController
  before_action :set_organogram, only: [:show, :edit, :update, :destroy]

  # GET /organograms
  # GET /organograms.json
  def index
    @organograms = Organogram.all
  end

  # GET /organograms/1
  # GET /organograms/1.json
  def show
  end

  # GET /organograms/new
  def new
    @organogram = Organogram.new
    @federations = Federation.all
    @juniorCompanies = JuniorCompany.all
  end

  # GET /organograms/1/edit
  def edit
    @federations = Federation.all
    @juniorCompanies = JuniorCompany.all
  end

  # POST /organograms
  # POST /organograms.json
  def create
    @organogram = Organogram.new(organogram_params)

    respond_to do |format|
      if @organogram.save
        format.html { redirect_to @organogram, notice: 'Organogram was successfully created.' }
        format.json { render :show, status: :created, location: @organogram }
      else
        format.html { render :new }
        format.json { render json: @organogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organograms/1
  # PATCH/PUT /organograms/1.json
  def update
    respond_to do |format|
      if @organogram.update(organogram_params)
        format.html { redirect_to @organogram, notice: 'Organogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @organogram }
      else
        format.html { render :edit }
        format.json { render json: @organogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organograms/1
  # DELETE /organograms/1.json
  def destroy
    @organogram.destroy
    respond_to do |format|
      format.html { redirect_to organograms_url, notice: 'Organogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organogram
      @organogram = Organogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organogram_params
      params.require(:organogram).permit(:federation_id, :junior_company_id, :date_initial, :date_final)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dimensions_helper.rb
module DimensionsHelper
end

app/helpers/organograms_helper.rb
module OrganogramsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/organograms/_form.html.erb
<%= form_for(@organogram) do |f| %>
  <% if @organogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organogram.errors.count, "error") %> prohibited this organogram from being saved:</h2>

      <ul>
      <% @organogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :federation_id %><br>
    <!-- <%= f.number_field :federation_id %> -->
    <%= collection_select(:organogram, :federation_id, @federations, :id, :name, {:prompt => false })  %>
  </div>
  <div class="field">
    <%= f.label :junior_company_id %><br>
    <!-- <%= f.number_field :junior_company_id %> -->
    <%= collection_select(:organogram, :junior_company_id, @juniorCompanies, :id, :name, {:prompt => false })  %>
  </div>
  <div class="field">
    <%= f.label :date_initial %><br>
    <%= f.date_select :date_initial %>
  </div>
  <div class="field">
    <%= f.label :date_final %><br>
    <%= f.date_select :date_final %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organograms/edit.html.erb
<h1>Editing Organogram</h1>

<%= render 'form' %>

<%= link_to 'Show', @organogram %> |
<%= link_to 'Back', organograms_path %>

app/views/organograms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organograms</h1>

<table>
  <thead>
    <tr>
      <th>Federation</th>
      <th>Junior company</th>
      <th>Date initial</th>
      <th>Date final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organograms.each do |organogram| %>
      <tr>
        <td><%= organogram.federation_id %></td>
        <td><%= organogram.junior_company_id %></td>
        <td><%= organogram.date_initial %></td>
        <td><%= organogram.date_final %></td>
        <td><%= link_to 'Show', organogram %></td>
        <td><%= link_to 'Edit', edit_organogram_path(organogram) %></td>
        <td><%= link_to 'Destroy', organogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organogram', new_organogram_path %>

app/views/organograms/new.html.erb
<h1>New Organogram</h1>

<%= render 'form' %>

<%= link_to 'Back', organograms_path %>

app/views/organograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Federation:</strong>
  <%= @organogram.federation_id %>
</p>

<p>
  <strong>Junior company:</strong>
  <%= @organogram.junior_company_id %>
</p>

<p>
  <strong>Date initial:</strong>
  <%= @organogram.date_initial %>
</p>

<p>
  <strong>Date final:</strong>
  <%= @organogram.date_final %>
</p>

<%= link_to 'Edit', edit_organogram_path(@organogram) %> |
<%= link_to 'Back', organograms_path %>