config/routes.rb
Rails.application.routes.draw do

  resources :indicator_junior_companies
  resources :indicator_federations
  resources :indicators
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "/perfomance_evaluation/:role_id" => "static_pages#perfomance_evaluation"
  get "/perfomance_result" => "static_pages#perfomance_result"
  get "/perfomance_areas" => "static_pages#perfomance_areas"
  get "/home" => "static_pages#home"
  get "/ajax_perfomance_user_save" => "static_pages#ajax_perfomance_user_save"

  get "/perfomance_answer" => "static_pages#perfomance_answer"
  devise_for :users, :controllers => { registrations: 'devise/registrations' }
  resources :questions
  resources :dimensions
  resources :perfomances
  resources :roles
  resources :areas
  resources :organograms
  resources :junior_companies
  resources :federations
  resources :cities
  resources :states
  resources :countries
  resources :roles

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to:organogram
  has_many:role
  has_many :subareas, class_name: "Area",
                          foreign_key: "subarea_id"
 
  belongs_to :subarea, class_name: "Area"
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to:state
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many:states
end

app/models/dimension.rb
class Dimension < ActiveRecord::Base
  belongs_to :perfomance
  has_many :questions
  has_many :perfomance_answers
end

app/models/federation.rb
class Federation < ActiveRecord::Base
  has_many :junior_companies
  has_many :organograms
  has_many :perfomaces
  has_many :indicator_federations
  has_many :indicators, through: :indicator_federations
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :indicator_junior_companies
  has_many :junior_companies, through: :indicator_junior_companies
  has_many :indicator_federations
  has_many :federations, through: :indicator_federations
end

app/models/junior_company.rb
class JuniorCompany < ActiveRecord::Base
  belongs_to :federation
  has_many :organograms
  has_many :perfomances
  has_many :indicator_junior_companies
  has_many :indicator, through: :indicator_junior_companies
end

app/models/organogram.rb
class Organogram < ActiveRecord::Base
  belongs_to:federation
  belongs_to:junior_company
  has_many:areas
  has_many:roles
end

app/models/perfomance.rb
class Perfomance < ActiveRecord::Base
  belongs_to :junior_companies
  belongs_to :federations
  belongs_to :role
  has_many :dimensions
  has_many :perfomance_answers
end

app/models/perfomance_answer.rb
class PerfomanceAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :perfomance
  belongs_to :dimension
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :dimension
  has_many :perfomance_answers
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to:organograms
  belongs_to:areas
  has_many:perfomances
  has_many:users
  has_many :suproles, class_name: "Role",
                          foreign_key: "suprole_id"
 
  belongs_to :suprole, class_name: "Role"
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to:country
  has_many:cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
    @countries = Country.all
  end

  # GET /states/1/edit
  def edit
    @countries = Country.all
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :country_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dimensions_helper.rb
module DimensionsHelper
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country_id %><br>
    <!-- <%= f.number_field :country_id %> -->
    <%= collection_select(:state, :country_id, @countries, :id, :name, {:prompt => false })  %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.country_id %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @state.country_id %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>