config/routes.rb
Rails.application.routes.draw do

  resources :indicator_junior_companies
  resources :indicator_federations
  resources :indicators
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "/perfomance_evaluation/:role_id" => "static_pages#perfomance_evaluation"
  get "/perfomance_result" => "static_pages#perfomance_result"
  get "/perfomance_areas" => "static_pages#perfomance_areas"
  get "/home" => "static_pages#home"
  get "/ajax_perfomance_user_save" => "static_pages#ajax_perfomance_user_save"

  get "/perfomance_answer" => "static_pages#perfomance_answer"
  devise_for :users, :controllers => { registrations: 'devise/registrations' }
  resources :questions
  resources :dimensions
  resources :perfomances
  resources :roles
  resources :areas
  resources :organograms
  resources :junior_companies
  resources :federations
  resources :cities
  resources :states
  resources :countries
  resources :roles

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to:organogram
  has_many:role
  has_many :subareas, class_name: "Area",
                          foreign_key: "subarea_id"
 
  belongs_to :subarea, class_name: "Area"
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to:state
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many:states
end

app/models/dimension.rb
class Dimension < ActiveRecord::Base
  belongs_to :perfomance
  has_many :questions
  has_many :perfomance_answers
end

app/models/federation.rb
class Federation < ActiveRecord::Base
  has_many :junior_companies
  has_many :organograms
  has_many :perfomaces
  has_many :indicator_federations
  has_many :indicators, through: :indicator_federations
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :indicator_junior_companies
  has_many :junior_companies, through: :indicator_junior_companies
  has_many :indicator_federations
  has_many :federations, through: :indicator_federations
end

app/models/indicator_federation.rb
class IndicatorFederation < ActiveRecord::Base
  belongs_to :indicator
  belongs_to :federation
end

app/models/junior_company.rb
class JuniorCompany < ActiveRecord::Base
  belongs_to :federation
  has_many :organograms
  has_many :perfomances
  has_many :indicator_junior_companies
  has_many :indicator, through: :indicator_junior_companies
end

app/models/organogram.rb
class Organogram < ActiveRecord::Base
  belongs_to:federation
  belongs_to:junior_company
  has_many:areas
  has_many:roles
end

app/models/perfomance.rb
class Perfomance < ActiveRecord::Base
  belongs_to :junior_companies
  belongs_to :federations
  belongs_to :role
  has_many :dimensions
  has_many :perfomance_answers
end

app/models/perfomance_answer.rb
class PerfomanceAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :perfomance
  belongs_to :dimension
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :dimension
  has_many :perfomance_answers
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to:organograms
  belongs_to:areas
  has_many:perfomances
  has_many:users
  has_many :suproles, class_name: "Role",
                          foreign_key: "suprole_id"
 
  belongs_to :suprole, class_name: "Role"
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to:country
  has_many:cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/indicator_federations_controller.rb
class IndicatorFederationsController < ApplicationController
  before_action :set_indicator_federation, only: [:show, :edit, :update, :destroy]

  # GET /indicator_federations
  # GET /indicator_federations.json
  def index
    @indicator_federations = IndicatorFederation.all
  end

  # GET /indicator_federations/1
  # GET /indicator_federations/1.json
  def show
  end

  # GET /indicator_federations/new
  def new
    @indicator_federation = IndicatorFederation.new
  end

  # GET /indicator_federations/1/edit
  def edit
  end

  # POST /indicator_federations
  # POST /indicator_federations.json
  def create
    @indicator_federation = IndicatorFederation.new(indicator_federation_params)

    respond_to do |format|
      if @indicator_federation.save
        format.html { redirect_to @indicator_federation.indicator}
        format.json { render :show, status: :created, location: @indicator_federation }
      else
        format.html { render :new }
        format.json { render json: @indicator_federation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicator_federations/1
  # PATCH/PUT /indicator_federations/1.json
  def update
    respond_to do |format|
      if @indicator_federation.update(indicator_federation_params)
        format.html { redirect_to @indicator_federation.indicator}
        format.json { render :show, status: :ok, location: @indicator_federation }
      else
        format.html { render :edit }
        format.json { render json: @indicator_federation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicator_federations/1
  # DELETE /indicator_federations/1.json
  def destroy
    @indicator_federation.destroy
    respond_to do |format|
      format.html { redirect_to @indicator_federation.indicator}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator_federation
      @indicator_federation = IndicatorFederation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_federation_params
      params.require(:indicator_federation).permit(:value, :federation_id, :indicator_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/indicator_federations_helper.rb
module IndicatorFederationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/indicator_federations/_form.html.erb
<%= simple_form_for(@indicator_federation) do |f| %>
  <% if @indicator_federation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indicator_federation.errors.count, "error") %> prohibited this indicator_federation from being saved:</h2>

      <ul>
      <% @indicator_federation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :value %>
  <%= f.association :indicator ,as: :select%>
  <%= f.association :federation ,as: :select %>
  <%= f.button :submit ,'Upadate'%>
<% end %>

app/views/indicator_federations/edit.html.erb
<h1>Editing Indicator Federation</h1>

<%= render 'form' %>

<%= link_to 'Show', @indicator_federation %> |
<%= link_to 'Back', indicator_federations_path %>

app/views/indicator_federations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Indicator Federations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicator_federations.each do |indicator_federation| %>
      <tr>
        <td><%= indicator_federation.name %></td>
        <td><%= indicator_federation.value %></td>
        <td><%= link_to 'Show', indicator_federation %></td>
        <td><%= link_to 'Edit', edit_indicator_federation_path(indicator_federation) %></td>
        <td><%= link_to 'Destroy', indicator_federation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indicator federation', new_indicator_federation_path %>

app/views/indicator_federations/new.html.erb
<h1>New Indicator Federation</h1>

<%= render 'form' %>

<%= link_to 'Back', indicator_federations_path %>

app/views/indicator_federations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @indicator_federation.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @indicator_federation.value %>
</p>

<%= link_to 'Edit', edit_indicator_federation_path(@indicator_federation) %> |
<%= link_to 'Back', indicator_federations_path %>